### ISSUE TITLE
Empty display names when contact alias is empty

### ISSUE THREAD

**Issue by ghost** [tieto/sipe#72]
When logging in old contacts from lync is "imported", the display names are empty, only showing the status icon and status message. Newly added contacts seems to get names

**Comment by xnandersson** [comment]
I have seen this also. But it is only the first time Pidgin SIPE is started. On the second startup the display names are there.

**Comment by xhaakon** [comment]
@Classe Is your company using Lync or Skype for Business?

**Comment by xhaakon** [comment]
The company is on Lync, which is probably irrelevant. The names aren't displayed on the first login only, after restart they show up...I blame Pidgin.

**Comment by xnandersson** [comment]
I don't know if something has changed, but last time I installed this odd behaviour wasn't there. I could see both icons, display names and status. If someone else can confirm after a first update we can probably close this one.

**Comment by xhaakon** [comment]
@xnandersson I've seen this at my colleague's Pidgin a while ago and don't think it has been fixed by us or Pidgin upstream. There must be a way to trigger the behavior; I only didn't have time to try to reproduce it yet.

**Comment by xhaakon** [comment]
This should be fixed in the following packages (Ubuntu builds on Launchpad are still pending at the time of writing):

```
pidgin-sipe - 1.21.1+sipe-0+201606141430~ubuntu14.04.1
pidgin-sipe - 1.21.1+sipe-0+201606141428~ubuntu15.10.1 
pidgin-sipe - 1.21.1+sipe-0+201606141428~ubuntu16.04.1
pidgin-sipe - 1.21.1-1+20160614132540~debian8
```

In order to test, it's enough to move away your `~/.purple` and then add your account anew into the clean configuration.

**Comment by xhaakon** [comment]
Two weeks have passed without any reported problems; closing as done.

**Comment by ahmedatawfik** [comment]
This problem is still there indeed. Using latest version of stock Pidgin on Ubuntu Xenial.

**Comment by ahmedatawfik** [comment]
![screenshot from 2017-12-20 10-27-53](https://user-images.githubusercontent.com/351319/34195864-a6db2c80-e570-11e7-843b-7c7bfed317f9.png)

Pidgin 2.10.12 (libpurple 2.10.12)
Sipe 1.20.1-1

**Comment by armyofda12mnkeys** [comment]
I just installed pidgen and also see all my company's contacts as blank since no default Alias.
Like so:
![image](https://user-images.githubusercontent.com/410112/34599090-99e817fe-f1be-11e7-9eea-8d4339f993c1.png)

Would be nice if it defaulted to whats in the name xml if no alias xml set in the blist.xml.
I tried to do the same steps in another person mentioned in 2015 of deleting 1 alias xml tag which claimed fixed issue after logging back into Pidgen:
(Theodoros Apazoglou  comment here: https://sourceforge.net/p/sipe/discussion/688534/thread/dd12cdc6/)

i installed pidgin and pidgin-sipe via this tutorial since I didnt see pidgin in the main sources when i did 'apt install pidgin' initially (Im on Ubuntu 16.04). https://garywoodfine.com/pidgin-office-365-lync/

So had to add sudo add-apt-repository ppa:jonathonf/backports
I'm at same versions like person above:
$ dkpg -s pidgin
Version: 1:2.10.12-0ubuntu5.2
$ dkpg -s pidgin-sipe
Version: 1.20.1-1
